FROM --platform=linux/amd64 ubuntu:20.04 as builder

## Install build dependencies.
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc

COPY . /acwj
WORKDIR /acwj/02_Parser
RUN make parser

FROM ubuntu:20.04 as package
COPY --from=builder /acwj/02_Parser/parser /
